config/routes.rb
Hckrfeed::Application.routes.draw do
  resources :comments


  resources :links do
    member do
      get :upvote
    end
  end
  root :to => 'links#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :link_id, :username

  belongs_to :link

  validates_presence_of :link_id
  validates_presence_of :comment
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :username, :name, :score

  has_many :comments, :dependent => :destroy

  validates_format_of :url, :with => %r{^http://}, :message => 'Must be a valid url - e.g. http://google.com'
  validates_presence_of :username
  validates_presence_of :name

  scope :date_desc, order('created_at DESC')
  scope :score_desc, order('score DESC')

  def increment_score!
    self.score += 1
    save!
  end

  def decrement_score!
    self.score -= 1
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    if params[:order] == 'date'
      @links = Link.date_desc
    else
      @links = Link.score_desc
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  def new
    @link = Link.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end
  def edit
    @link = Link.find(params[:id])
  end

  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.increment_score!

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_ago(datetime)
    time_ago_in_words(datetime) + ' ago'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_form.html.haml
= form_for @comment, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :username, :class => 'control-label'
    .controls
      = f.text_field :username, :class => 'text_field'
      = f.error_message_on :username
  .control-group
    = f.label :comment, :class => 'control-label'
    .controls
      = f.text_field :comment, :class => 'text_field'
      = f.error_message_on :comment
  .control-group
    = f.label :link_id, :class => 'control-label'
    .controls
      = f.collection_select(:link_id, Link.all, :id, :name)
      = f.error_message_on :link_id
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), comments_path, :class => 'btn'

app/views/comments/edit.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/comments/index.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th
      %th Username
      %th Comment
      %th Link
      %th
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @comments.each do |comment|
      %tr
        %td= link_to 'Show', comment_path(comment)
        %td= comment.username
        %td= comment.comment
        %td= link_to comment.link.name, link_path(comment.link_id)
        %td= time_ago(comment.created_at)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(comment), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(comment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_comment_path, :class => 'btn btn-primary'

app/views/comments/new.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/comments/show.html.haml
- model_class = Comment
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @comment.username
%p
  %strong= model_class.human_attribute_name(:comment) + ':'
  %br
  = @comment.comment
%p
  %strong= model_class.human_attribute_name(:link_id) + ':'
  %br
  = link_to @comment.link.name, link_path(@comment.link_id)

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), comments_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_comment_path(@comment), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), comment_path(@comment), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Hckrfeed"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Hckrfeed
          .container.nav-collapse
            %ul.nav

    .container-fluid

      .row-fluid
        .span12
          = bootstrap_flash
          = yield
    
      %footer
        %br
        %p &copy; Hckrfeed 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/links/_form.html.haml
= form_for @link, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :username, :class => 'control-label'
    .controls
      = f.text_field :username, :class => 'text_field'
      = f.error_message_on :username
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
      = f.error_message_on :name
  .control-group
    = f.label :url, :class => 'control-label'
    .controls
      = f.text_field :url, :class => 'text_field'
      = f.error_message_on :url
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), links_path, :class => 'btn'

app/views/links/edit.html.haml
- model_class = Link
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/links/index.html.haml
- model_class = Link
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped#links
  %thead
    %tr
      %th
      %th Score
      %th Name
      %th
      %th Username
      %th
      %th
  %tbody
    - @links.each do |link|
      %tr
        %td= link_to 'Upvote', upvote_link_path(link), id: "upvote_#{link.id}", class: "upvote" 
        %td= link.score
        %td= link_to link.name, link_path(link)
        %td= link_to "#{link.comments.count} comments", link_path(link)
        %td= link.username
        %td= time_ago(link.created_at)
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_link_path(link), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), link_path(link), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.submit_link")), new_link_path, :class => 'btn btn-primary', :id => 'fuck'

app/views/links/new.html.haml
- model_class = Link
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/links/show.html.haml
- model_class = Link
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong Name:
  %br
  =link_to @link.name, @link.url
%p
  %strong Username:
  %br
  = @link.username
%p
  %strong Score:
  %br
  = @link.score
%p
  %strong Created:
  %br
  = time_ago(@link.created_at)

%br

%a#comments
%table.table.table-striped
  %thead
    %tr
      %th Comments
      %th Username
      %th Comment
      %th
  - @link.comments.each do |comment|
    %tbody
      %tr
        %td= link_to 'Show', comment_path(comment)
        %td= comment.username
        %td= comment.comment
        %td= link_to comment.link.name, link_path(comment.link_id)
        %td= time_ago(comment.created_at)

= link_to 'New Comment', new_comment_path

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), links_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_link_path(@link), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), link_path(@link), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'